---
- name: install k8s with crio
  hosts: ctrls,wrks
  become: yes
  gather_facts: yes
  roles:
    - hostname
    - cloud_init
    - common_k8s

- name: install k8s
  hosts: ctrls
  become: yes
  gather_facts: yes
  roles:
    - install_master_k8s