---
- name: install packages
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - common_k8s

- name: install k8s
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - install_master_k8s